name: cd
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v2
      - uses: asdf-vm/actions/install@v1
      - run: pip install git+https://${GH_TOKEN}@github.com/tpucci/mkdocs-material-insiders.git
      - run: mkdocs gh-deploy --force
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
